import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Providers from "./chakra-providers";
import StoreProvider from "./store-provider";
import { ToastContainer } from "react-toastify";
import Clientwrapper from "./clientwrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Hair Saga",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <StoreProvider>
          {/* <Providers> */}
          <ToastContainer position="top-right" autoClose={4000} />
          <Clientwrapper>{children}</Clientwrapper>
          {/* </Providers> */}
        </StoreProvider>
      </body>
    </html>
  );
}
